[functions]
  directory = "netlify/functions"

# Zorg dat /api/log naar de function wijst
[[redirects]]
  from = "/api/log"
  to = "/.netlify/functions/log"
  status = 200

# (optioneel) geen cache op demo-pagina's
[[headers]]
  for = "/game.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/stats.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

