# build_companion_docs.py
# Genereert per naamgever een companion.json (schema uit spec §9), met de weetjes als
# array zodat de companion telkens een WILLEKEURIGE weetje kan tonen.
# Draai:  python build_companion_docs.py
# Output: companion-<key>.json per lokaal -> upload elk als document "companion.json"
#         op de betreffende Space in Ultimo.

import json
from pathlib import Path

facts = {
    "BREL — Jacques Brel": [
        {"NL": "In 1953 nam Brel zijn eerste 78-toerenplaat op. Zes jaar later nam hij Ne me quitte pas op.",
         "FR": "En 1953, Brel enregistre son premier 78 tours. Six ans plus tard, il enregistre Ne me quitte pas.",
         "EN": "In 1953, Brel recorded his first 78 rpm record. Six years later, he recorded Ne me quitte pas."},
        {"NL": "Amsterdam werd in 1964 opgenomen tijdens Brels passage in de Olympia in Parijs.",
         "FR": "Amsterdam est enregistré en 1964 lors du passage de Brel à l’Olympia de Paris.",
         "EN": "Amsterdam was recorded in 1964 during Brel’s appearance at the Olympia in Paris."},
        {"NL": "In 1966 besliste Brel te stoppen met tournees. Zijn allerlaatste podiumoptreden volgde in 1967 in Roubaix.",
         "FR": "En 1966, Brel décide d’arrêter les tournées. Sa toute dernière prestation sur scène a lieu en 1967 à Roubaix.",
         "EN": "In 1966, Brel decided to stop touring. His final stage performance followed in 1967 in Roubaix."},
        {"NL": "In 1974 verliet Brel Antwerpen op zijn zeilboot Askoy II.",
         "FR": "En 1974, Brel quitte Anvers à bord de son voilier Askoy II.",
         "EN": "In 1974, Brel left Antwerp aboard his sailing boat Askoy II."},
        {"NL": "In 1975 stak Brel de Stille Oceaan over richting Polynesië.",
         "FR": "En 1975, Brel traverse le Pacifique en direction de la Polynésie.",
         "EN": "In 1975, Brel crossed the Pacific Ocean towards Polynesia."},
        {"NL": "In 1976 vestigde Brel zich op Hiva Oa, een eiland in de Marquesas.",
         "FR": "En 1976, Brel s’installe à Hiva Oa, une île des Marquises.",
         "EN": "In 1976, Brel settled on Hiva Oa, an island in the Marquesas."},
        {"NL": "Brel ligt begraven op Hiva Oa, het eiland waar hij zijn laatste levensjaren doorbracht.",
         "FR": "Brel repose à Hiva Oa, l’île où il a passé les dernières années de sa vie.",
         "EN": "Brel is buried on Hiva Oa, the island where he spent the final years of his life."},
        {"NL": "In 1977 nam Brel zijn laatste plaat Les Marquises op.",
         "FR": "En 1977, Brel enregistre son dernier disque, Les Marquises.",
         "EN": "In 1977, Brel recorded his final album, Les Marquises."},
        {"NL": "Brel was ook filmregisseur: hij regisseerde Franz en Le Far West.",
         "FR": "Brel était aussi réalisateur : il a réalisé Franz et Le Far West.",
         "EN": "Brel was also a film director: he directed Franz and Le Far West."},
        {"NL": "In 1968 maakte Brel de Franse versie van de musical L’Homme de la Mancha.",
         "FR": "En 1968, Brel crée la version française de la comédie musicale L’Homme de la Mancha.",
         "EN": "In 1968, Brel created the French version of the musical Man of La Mancha."},
        {"NL": "Brel richtte in 1962 zijn eigen muziekuitgeverij Éditions Pouchenel op.",
         "FR": "En 1962, Brel crée sa propre maison d’édition musicale, les Éditions Pouchenel.",
         "EN": "In 1962, Brel founded his own music publishing company, Éditions Pouchenel."},
        {"NL": "In augustus 1953 nam Brel bij Radio Hasselt zijn volledige repertoire op.",
         "FR": "En août 1953, Brel enregistre tout son répertoire à Radio Hasselt.",
         "EN": "In August 1953, Brel recorded his entire repertoire at Radio Hasselt."},
        {"NL": "Brel stond in 1961 voor het eerst als hoofdact in de Olympia.",
         "FR": "En 1961, Brel se produit pour la première fois en vedette à l’Olympia.",
         "EN": "In 1961, Brel appeared as the headline act at the Olympia for the first time."},
        {"NL": "In 1969 nam Brel ook Het verhaal van Babar en Peter en de Wolf op.",
         "FR": "En 1969, Brel enregistre aussi L’Histoire de Babar et Pierre et le Loup.",
         "EN": "In 1969, Brel also recorded The Story of Babar and Peter and the Wolf."},
        {"NL": "In 1967 gaf Brel zijn laatste concert én begon hij aan een nieuwe carrière als filmacteur.",
         "FR": "En 1967, Brel donne son dernier concert et entame une nouvelle carrière d’acteur de cinéma.",
         "EN": "In 1967, Brel gave his final concert and began a new career as a film actor."},
    ],
    "HORTA — Victor Horta": [
        {"NL": "Bij Horta kreeg zelfs een deurbel of deurklink dezelfde ontwerpaandacht als het meubilair.",
         "FR": "Chez Horta, même une sonnette ou une poignée de porte recevait autant d’attention que le mobilier.",
         "EN": "For Horta, even a doorbell or door handle received the same design attention as the furniture."},
        {"NL": "Vier Brusselse huizen van Horta staan samen op de UNESCO-Werelderfgoedlijst.",
         "FR": "Quatre maisons bruxelloises de Horta sont inscrites ensemble au patrimoine mondial de l’UNESCO.",
         "EN": "Four of Horta’s Brussels houses are jointly listed as UNESCO World Heritage."},
        {"NL": "Hôtel Tassel uit 1893 geldt als een van de baanbrekende werken van de vroege art nouveau.",
         "FR": "L’Hôtel Tassel de 1893 est considéré comme l’une des œuvres pionnières de l’Art nouveau.",
         "EN": "The 1893 Hôtel Tassel is considered one of the pioneering works of early Art Nouveau."},
        {"NL": "Horta liet gebogen decoratielijnen letterlijk samenvloeien met de structuur van het gebouw.",
         "FR": "Horta faisait littéralement fusionner les lignes courbes du décor avec la structure du bâtiment.",
         "EN": "Horta literally merged curved decorative lines with the structure of the building."},
        {"NL": "Staal en glas waren bij Horta geen elementen om te verbergen. Ze maakten deel uit van de architectuur.",
         "FR": "Chez Horta, l’acier et le verre n’étaient pas à cacher. Ils faisaient partie de l’architecture.",
         "EN": "For Horta, steel and glass were not elements to hide. They were part of the architecture."},
        {"NL": "Open ruimtes en de verspreiding van licht maakten Horta’s huizen revolutionair aan het einde van de 19e eeuw.",
         "FR": "Les espaces ouverts et la diffusion de la lumière rendaient les maisons de Horta révolutionnaires à la fin du XIXe siècle.",
         "EN": "Open spaces and the diffusion of light made Horta’s houses revolutionary at the end of the 19th century."},
        {"NL": "Hôtel Tassel en Hôtel van Eetvelde zijn opgebouwd als dubbele huizen, verbonden door een glazen circulatieruimte.",
         "FR": "L’Hôtel Tassel et l’Hôtel van Eetvelde sont conçus comme des maisons doubles reliées par un espace de circulation vitré.",
         "EN": "Hôtel Tassel and Hôtel van Eetvelde were designed as double houses connected by a glass-covered circulation space."},
        {"NL": "De glazen verbindingsruimtes in Horta’s huizen bevatten vaak een wintertuin.",
         "FR": "Les espaces vitrés qui reliaient les parties des maisons de Horta abritaient souvent un jardin d’hiver.",
         "EN": "The glass-covered connecting spaces in Horta’s houses often contained a winter garden."},
        {"NL": "UNESCO noemt Hôtel Solvay Horta’s meest ambitieuze en spectaculaire art-nouveauwerk.",
         "FR": "L’UNESCO qualifie l’Hôtel Solvay d’œuvre Art nouveau la plus ambitieuse et spectaculaire de Horta.",
         "EN": "UNESCO describes Hôtel Solvay as Horta’s most ambitious and spectacular Art Nouveau work."},
        {"NL": "Horta ontwierp elk huis zodat het de persoonlijkheid van de eigenaar weerspiegelde.",
         "FR": "Horta concevait chaque maison pour qu’elle reflète la personnalité de son propriétaire.",
         "EN": "Horta designed each house to reflect the personality of its owner."},
        {"NL": "Voor Horta waren architectuur en decoratie geen aparte vakken. Alles moest één geheel vormen.",
         "FR": "Pour Horta, l’architecture et la décoration n’étaient pas séparées. Tout devait former un ensemble.",
         "EN": "For Horta, architecture and decoration were not separate disciplines. Everything had to form one whole."},
        {"NL": "In 1919 kreeg Horta de opdracht om het Brusselse Paleis voor Schone Kunsten te ontwerpen.",
         "FR": "En 1919, Horta reçoit la mission de concevoir le Palais des Beaux-Arts de Bruxelles.",
         "EN": "In 1919, Horta was commissioned to design Brussels’ Centre for Fine Arts."},
        {"NL": "Voor het huidige BOZAR ruilde Horta de golvende art-nouveaulijnen in voor de geometrie van de art deco.",
         "FR": "Pour l’actuel BOZAR, Horta abandonne les lignes sinueuses de l’Art nouveau au profit de la géométrie Art déco.",
         "EN": "For today’s BOZAR, Horta traded the flowing lines of Art Nouveau for the geometry of Art Deco."},
        {"NL": "Horta noemde het Paleis voor Schone Kunsten zelf een hoogtepunt in zijn carrière.",
         "FR": "Horta qualifiait lui-même le Palais des Beaux-Arts de sommet de sa carrière.",
         "EN": "Horta himself described the Centre for Fine Arts as a high point in his career."},
        {"NL": "Het Brusselse Paleis voor Schone Kunsten opende in 1928 voor het publiek.",
         "FR": "Le Palais des Beaux-Arts de Bruxelles a ouvert ses portes au public en 1928.",
         "EN": "Brussels’ Centre for Fine Arts opened to the public in 1928."},
    ],
    "MERCKX — Eddy Merckx": [
        {"NL": "Eddy Merckx won elf Grote Rondes: vijf Tours, vijf Giro’s en één Vuelta.",
         "FR": "Eddy Merckx a remporté onze Grands Tours : cinq Tours, cinq Giros et une Vuelta.",
         "EN": "Eddy Merckx won eleven Grand Tours: five Tours, five Giros and one Vuelta."},
        {"NL": "Merckx won negentien Monumenten. Dat is nog altijd het record.",
         "FR": "Merckx a remporté dix-neuf Monuments. C’est toujours le record.",
         "EN": "Merckx won nineteen Monuments. That is still the record."},
        {"NL": "Milaan-San Remo won Merckx zeven keer.",
         "FR": "Merckx a remporté Milan-San Remo à sept reprises.",
         "EN": "Merckx won Milan-San Remo seven times."},
        {"NL": "Merckx won tijdens zijn carrière alle vijf de wielerMonumenten.",
         "FR": "Au cours de sa carrière, Merckx a remporté les cinq Monuments du cyclisme.",
         "EN": "During his career, Merckx won all five of cycling’s Monuments."},
        {"NL": "In 1974 won Merckx de Giro, de Tour én het wereldkampioenschap in hetzelfde jaar.",
         "FR": "En 1974, Merckx remporte le Giro, le Tour et le championnat du monde la même année.",
         "EN": "In 1974, Merckx won the Giro, the Tour and the World Championship in the same year."},
        {"NL": "Merckx was in 1974 de eerste man die de beroemde Triple Crown van Giro, Tour en WK pakte.",
         "FR": "En 1974, Merckx devient le premier homme à réaliser la célèbre Triple Couronne : Giro, Tour et Mondial.",
         "EN": "In 1974, Merckx became the first man to achieve the famous Triple Crown: Giro, Tour and World Championship."},
        {"NL": "Merckx droeg 111 dagen de gele trui in de Tour. Niemand deed dat vaker.",
         "FR": "Merckx a porté le maillot jaune pendant 111 jours sur le Tour. Personne ne l’a fait plus souvent.",
         "EN": "Merckx wore the Tour’s yellow jersey for 111 days. No one has done it more often."},
        {"NL": "Bij zijn eerste Tourdeelname in 1969 won Merckx meteen het eindklassement.",
         "FR": "Pour sa première participation au Tour en 1969, Merckx remporte directement le classement général.",
         "EN": "In his first Tour de France in 1969, Merckx immediately won the overall classification."},
        {"NL": "In de Tour van 1969 won Merckx het algemeen klassement, het puntenklassement én het bergklassement.",
         "FR": "Lors du Tour 1969, Merckx remporte le classement général, le classement par points et le classement de la montagne.",
         "EN": "At the 1969 Tour, Merckx won the general, points and mountains classifications."},
        {"NL": "Merckx nam in 1964 als 19-jarige amateur deel aan de Olympische Spelen van Tokio.",
         "FR": "En 1964, Merckx participe aux Jeux olympiques de Tokyo comme amateur de 19 ans.",
         "EN": "In 1964, Merckx competed at the Tokyo Olympics as a 19-year-old amateur."},
        {"NL": "Merckx won 64 ritten in de drie Grote Rondes samen.",
         "FR": "Merckx a remporté 64 étapes dans l’ensemble des trois Grands Tours.",
         "EN": "Merckx won 64 stages across the three Grand Tours."},
        {"NL": "Alleen al in de Tour de France won Merckx 34 ritten.",
         "FR": "Rien que sur le Tour de France, Merckx a remporté 34 étapes.",
         "EN": "In the Tour de France alone, Merckx won 34 stages."},
        {"NL": "Merckx won 24 ritten in de Giro en zes in de Vuelta.",
         "FR": "Merckx a remporté 24 étapes sur le Giro et six sur la Vuelta.",
         "EN": "Merckx won 24 Giro stages and six Vuelta stages."},
        {"NL": "Merckx werd drie keer wereldkampioen op de weg.",
         "FR": "Merckx a été trois fois champion du monde sur route.",
         "EN": "Merckx became road world champion three times."},
        {"NL": "Zijn bijnaam De Kannibaal kreeg Merckx omdat hij bleef aanvallen en winnen, zelfs wanneer hij al domineerde.",
         "FR": "Merckx a reçu le surnom de Cannibale parce qu’il continuait à attaquer et à gagner, même lorsqu’il dominait déjà.",
         "EN": "Merckx earned the nickname The Cannibal because he kept attacking and winning, even when he was already dominant."},
    ],
    "TOOTS — Toots Thielemans": [
        {"NL": "Miljoenen kinderen hoorden Toots zonder het te weten: hij speelde mondharmonica op de tune van Sesamstraat.",
         "FR": "Des millions d’enfants ont entendu Toots sans le savoir : il jouait de l’harmonica sur le générique de Sesame Street.",
         "EN": "Millions of children heard Toots without knowing it: he played harmonica on the Sesame Street theme."},
        {"NL": "Het herkenbare gefluit in een Amerikaanse Old Spice-reclame? Ook dat was Toots.",
         "FR": "Le sifflement reconnaissable d’une publicité américaine Old Spice ? C’était aussi Toots.",
         "EN": "The distinctive whistling in an American Old Spice commercial? That was Toots too."},
        {"NL": "Eén plaat van Louis Armstrong in 1940 zette Toots definitief op het spoor van de jazz.",
         "FR": "Un disque de Louis Armstrong entendu en 1940 a définitivement orienté Toots vers le jazz.",
         "EN": "A Louis Armstrong record he heard in 1940 set Toots firmly on the path to jazz."},
        {"NL": "Toots leerde accordeon spelen toen hij amper drie jaar oud was.",
         "FR": "Toots a appris à jouer de l’accordéon à seulement trois ans.",
         "EN": "Toots learned to play the accordion when he was only three years old."},
        {"NL": "Op zijn zeventiende begon Toots chromatische mondharmonica te spelen.",
         "FR": "À dix-sept ans, Toots commence à jouer de l’harmonica chromatique.",
         "EN": "At seventeen, Toots began playing chromatic harmonica."},
        {"NL": "Gitaar leerde Toots zichzelf aan.",
         "FR": "Toots a appris la guitare tout seul.",
         "EN": "Toots taught himself to play the guitar."},
        {"NL": "In 1950 toerde Toots als gitarist door Europa met het sextet van Benny Goodman.",
         "FR": "En 1950, Toots tourne en Europe comme guitariste avec le sextet de Benny Goodman.",
         "EN": "In 1950, Toots toured Europe as a guitarist with the Benny Goodman Sextet."},
        {"NL": "In 1952 verhuisde de Brusselaar Toots naar de Verenigde Staten.",
         "FR": "En 1952, le Bruxellois Toots s’installe aux États-Unis.",
         "EN": "In 1952, Brussels-born Toots moved to the United States."},
        {"NL": "Toots kreeg in Amerika de kans om met Charlie Parker’s All-Stars te spelen.",
         "FR": "Aux États-Unis, Toots a eu l’occasion de jouer avec les All-Stars de Charlie Parker.",
         "EN": "In America, Toots got the chance to play with Charlie Parker’s All-Stars."},
        {"NL": "George Shearing was zo onder de indruk van Toots dat hij hem meteen in zijn band opnam.",
         "FR": "George Shearing était tellement impressionné par Toots qu’il l’a invité à rejoindre son groupe.",
         "EN": "George Shearing was so impressed by Toots that he invited him to join his band."},
        {"NL": "Voor Bluesette liet Toots zijn gitaar en zijn gefluit exact dezelfde melodie spelen.",
         "FR": "Pour Bluesette, Toots faisait jouer exactement la même mélodie à sa guitare et à son sifflement.",
         "EN": "For Bluesette, Toots had his guitar and his whistling play exactly the same melody."},
        {"NL": "Toots speelde en nam muziek op met onder anderen Ella Fitzgerald, Quincy Jones, Bill Evans, Paul Simon en Billy Joel.",
         "FR": "Toots a joué et enregistré avec Ella Fitzgerald, Quincy Jones, Bill Evans, Paul Simon et Billy Joel, entre autres.",
         "EN": "Toots played and recorded with Ella Fitzgerald, Quincy Jones, Bill Evans, Paul Simon and Billy Joel, among others."},
        {"NL": "De mondharmonica van Toots is prominent te horen op de soundtrack van Midnight Cowboy.",
         "FR": "L’harmonica de Toots est très présent sur la bande originale de Midnight Cowboy.",
         "EN": "Toots’ harmonica is prominently heard on the Midnight Cowboy soundtrack."},
        {"NL": "Op het jazzfestival van Montreux nam Toots op met Oscar Peterson en later met Dizzy Gillespie.",
         "FR": "Au festival de jazz de Montreux, Toots a enregistré avec Oscar Peterson puis avec Dizzy Gillespie.",
         "EN": "At the Montreux Jazz Festival, Toots recorded with Oscar Peterson and later with Dizzy Gillespie."},
        {"NL": "In 2001 gaf koning Albert II Toots de titel van baron. In 2009 werd hij ook NEA Jazz Master.",
         "FR": "En 2001, le roi Albert II accorde à Toots le titre de baron. En 2009, il devient aussi NEA Jazz Master.",
         "EN": "In 2001, King Albert II bestowed the title of Baron on Toots. In 2009, he also became an NEA Jazz Master."},
    ],
    "HERGÉ — Georges Remi": [
        {"NL": "Hergé heette eigenlijk Georges Remi. Zijn artiestennaam komt van zijn omgekeerde initialen R.G., uitgesproken op zijn Frans.",
         "FR": "Hergé s’appelait en réalité Georges Remi. Son nom d’artiste vient de ses initiales inversées R.G., prononcées en français.",
         "EN": "Hergé’s real name was Georges Remi. His pen name came from reversing his initials, R.G., as pronounced in French."},
        {"NL": "Als scout kreeg Hergé de bijnaam Curious Fox. Zijn eerste tekeningen verschenen in scoutstijdschriften.",
         "FR": "Chez les scouts, Hergé reçoit le surnom de Curious Fox. Ses premiers dessins paraissent dans des revues scoutes.",
         "EN": "As a scout, Hergé was nicknamed Curious Fox. His first drawings appeared in scouting magazines."},
        {"NL": "Voor Kuifje was er Totor, een scout die officieel geldt als de voorloper van Kuifje.",
         "FR": "Avant Tintin, il y avait Totor, un scout officiellement considéré comme le précurseur de Tintin.",
         "EN": "Before Tintin, there was Totor, a scout officially regarded as Tintin’s precursor."},
        {"NL": "In 1928 werd Hergé hoofdredacteur van Le Petit Vingtième, het kinderblad waarin Kuifje zou ontstaan.",
         "FR": "En 1928, Hergé devient rédacteur en chef du Petit Vingtième, le supplément jeunesse où Tintin allait naître.",
         "EN": "In 1928, Hergé became editor-in-chief of Le Petit Vingtième, the children’s supplement where Tintin would be born."},
        {"NL": "Kuifje en Bobbie verschenen voor het eerst op 10 januari 1929.",
         "FR": "Tintin et Milou apparaissent pour la première fois le 10 janvier 1929.",
         "EN": "Tintin and Snowy first appeared on 10 January 1929."},
        {"NL": "Een jaar na Kuifje bedacht Hergé ook Quick en Flupke, twee Brusselse kwajongens.",
         "FR": "Un an après Tintin, Hergé crée aussi Quick et Flupke, deux gamins de Bruxelles.",
         "EN": "One year after Tintin, Hergé also created Quick and Flupke, two Brussels rascals."},
        {"NL": "Een ontmoeting met de Chinese student Chang Chong-Chen veranderde Hergés manier van werken voorgoed.",
         "FR": "La rencontre avec l’étudiant chinois Tchang Tchong-Jen a changé définitivement la manière de travailler de Hergé.",
         "EN": "Meeting Chinese student Chang Chong-Chen changed Hergé’s way of working for good."},
        {"NL": "Door Chang begon Hergé veel grondiger te documenteren. Het betekende een keerpunt voor De Blauwe Lotus.",
         "FR": "Grâce à Tchang, Hergé commence à se documenter beaucoup plus rigoureusement. Ce fut un tournant pour Le Lotus bleu.",
         "EN": "Thanks to Chang, Hergé began researching far more rigorously. It became a turning point for The Blue Lotus."},
        {"NL": "Chang inspireerde Hergé zo sterk dat hij een Kuifje-personage naar hem vernoemde.",
         "FR": "Tchang a tellement inspiré Hergé qu’un personnage de Tintin porte son nom.",
         "EN": "Chang inspired Hergé so deeply that a Tintin character was named after him."},
        {"NL": "Naast Kuifje creëerde Hergé ook Jo, Zette en Jocko.",
         "FR": "En plus de Tintin, Hergé a aussi créé Jo, Zette et Jocko.",
         "EN": "Besides Tintin, Hergé also created Jo, Zette and Jocko."},
        {"NL": "De Studios Hergé brachten tekenaars, inkleurders, schrijvers, onderzoekers en zelfs wetenschappelijke kennis samen.",
         "FR": "Les Studios Hergé réunissaient dessinateurs, coloristes, auteurs, chercheurs et même des compétences scientifiques.",
         "EN": "The Hergé Studios brought together artists, colourists, writers, researchers and even scientific expertise."},
        {"NL": "In de Studios Hergé werd elk vakje, elke dialoog en elke achtergrond besproken en herwerkt.",
         "FR": "Aux Studios Hergé, chaque case, chaque dialogue et chaque décor était discuté et retravaillé.",
         "EN": "At the Hergé Studios, every panel, every line of dialogue and every background was discussed and reworked."},
        {"NL": "Bob De Moor werd Hergés rechterhand en deed terreinonderzoek met foto’s en architecturale details.",
         "FR": "Bob De Moor devient le bras droit de Hergé et mène des recherches de terrain avec photos et détails architecturaux.",
         "EN": "Bob De Moor became Hergé’s right-hand man and carried out field research using photographs and architectural details."},
        {"NL": "Voor Raket naar de maan werden zelfs wetenschappelijke installaties bezocht om volumes en verhoudingen correct te krijgen.",
         "FR": "Pour Objectif Lune, des installations scientifiques ont même été visitées afin de respecter les volumes et les proportions.",
         "EN": "For Destination Moon, scientific facilities were even visited to get volumes and proportions right."},
        {"NL": "In 1982 kreeg Hergé een planeet tussen Mars en Jupiter naar zich genoemd.",
         "FR": "En 1982, une planète située entre Mars et Jupiter a été baptisée du nom de Hergé.",
         "EN": "In 1982, a planet located between Mars and Jupiter was named after Hergé."},
    ],
    "RUBENS — Peter Paul Rubens": [
        {"NL": "Rubens werd niet in Antwerpen geboren, maar in het Duitse Siegen.",
         "FR": "Rubens n’est pas né à Anvers, mais à Siegen, en Allemagne.",
         "EN": "Rubens was not born in Antwerp, but in the German town of Siegen."},
        {"NL": "Rubens had er bijna nooit geweest: zijn vader was vóór zijn geboorte ter dood veroordeeld na een affaire met Anna van Saksen.",
         "FR": "Rubens aurait presque pu ne jamais naître : avant sa naissance, son père avait été condamné à mort après une liaison avec Anne de Saxe.",
         "EN": "Rubens almost never existed: before his birth, his father had been sentenced to death after an affair with Anna of Saxony."},
        {"NL": "Dankzij zijn moeder werd de doodstraf van Rubens’ vader omgezet in ballingschap.",
         "FR": "Grâce à sa mère, la peine de mort du père de Rubens a été transformée en exil.",
         "EN": "Thanks to his mother, the death sentence against Rubens’ father was commuted to exile."},
        {"NL": "Van de twaalfjarige Rubens zijn 42 vroege inkttekeningen bekend.",
         "FR": "On connaît 42 dessins à l’encre réalisés par Rubens à l’âge de douze ans.",
         "EN": "Forty-two early ink drawings by the twelve-year-old Rubens are known today."},
        {"NL": "Rubens trok in 1600 naar Italië en bleef er ongeveer acht jaar om renaissancekunst en de oudheid te bestuderen.",
         "FR": "En 1600, Rubens part en Italie et y reste environ huit ans pour étudier la Renaissance et l’Antiquité.",
         "EN": "In 1600, Rubens travelled to Italy and stayed for about eight years to study Renaissance art and classical antiquity."},
        {"NL": "Rubens werd hofschilder van aartshertogen Albrecht en Isabella en moest alleen aan de vorsten verantwoording afleggen.",
         "FR": "Rubens devient peintre de cour des archiducs Albert et Isabelle et ne dépend directement que des souverains.",
         "EN": "Rubens became court painter to Archdukes Albert and Isabella and answered directly only to the sovereigns."},
        {"NL": "Voor zijn huis aan de Wapper betaalde Rubens 8.960 gulden én een van zijn eigen schilderijen.",
         "FR": "Pour sa maison au Wapper, Rubens paie 8 960 florins et ajoute l’un de ses propres tableaux.",
         "EN": "For his house on the Wapper, Rubens paid 8,960 guilders and added one of his own paintings."},
        {"NL": "Rubens verbouwde zijn Antwerpse woning tot een Italiaans stadspaleis met atelier, tuin en beeldenmuseum.",
         "FR": "Rubens transforme sa maison anversoise en palais italien avec atelier, jardin et musée de sculptures.",
         "EN": "Rubens transformed his Antwerp home into an Italian-style city palace with a studio, garden and sculpture museum."},
        {"NL": "De koepel boven Rubens’ beeldenmuseum was een primeur in onze regio en was geïnspireerd op het Pantheon in Rome.",
         "FR": "La coupole du musée de sculptures de Rubens était une première dans notre région et s’inspirait du Panthéon de Rome.",
         "EN": "The dome above Rubens’ sculpture museum was a first in the region and was inspired by the Pantheon in Rome."},
        {"NL": "Anthony van Dyck kon Rubens’ stijl zo overtuigend nabootsen dat hij soms als zijn vervanger optrad.",
         "FR": "Anthony van Dyck imitait le style de Rubens avec une telle précision qu’il pouvait parfois le remplacer.",
         "EN": "Anthony van Dyck could imitate Rubens’ style so convincingly that he sometimes acted as his stand-in."},
        {"NL": "Een bezoeker zag Rubens tegelijk schilderen, naar Tacitus in het Latijn luisteren en een brief dicteren.",
         "FR": "Un visiteur a vu Rubens peindre, écouter Tacite en latin et dicter une lettre en même temps.",
         "EN": "A visitor saw Rubens painting, listening to Tacitus in Latin and dictating a letter at the same time."},
        {"NL": "Rubens gebruikte een internationaal netwerk van graveurs om zijn werk wereldwijd bekend te maken.",
         "FR": "Rubens utilisait un réseau international de graveurs pour faire connaître son œuvre au-delà des frontières.",
         "EN": "Rubens used an international network of engravers to spread his work across borders."},
        {"NL": "Zijn werk werd met officiële privileges tegen namaak beschermd. Rubens kopiëren werd bijna als industriële spionage gezien.",
         "FR": "Des privilèges officiels protégeaient son œuvre contre la copie. Copier Rubens était presque considéré comme de l’espionnage industriel.",
         "EN": "Official privileges protected his work against copying. Copying Rubens was treated almost like industrial espionage."},
        {"NL": "Rubens werkte als geheim agent en diplomaat aan vrede tussen Spanje en Engeland en werd twee keer tot ridder geslagen.",
         "FR": "Rubens a travaillé comme agent secret et diplomate pour la paix entre l’Espagne et l’Angleterre et a été anobli deux fois.",
         "EN": "Rubens worked as a secret agent and diplomat for peace between Spain and England and was knighted twice."},
        {"NL": "Rubens’ jongste dochter werd acht maanden na zijn dood geboren.",
         "FR": "La plus jeune fille de Rubens est née huit mois après sa mort.",
         "EN": "Rubens’ youngest daughter was born eight months after his death."},
    ],
}

sources = {
    "BREL — Jacques Brel": ["https://fondationbrel.be/biographie-brel/"],
    "HORTA — Victor Horta": [
        "https://whc.unesco.org/en/list/1005/",
        "https://www.bozar.be/en/four-aspects-architecture",
        "https://www.bozar.be/en/building",
    ],
    "MERCKX — Eddy Merckx": [
        "https://www.olympics.com/en/athletes/eddy-merckx",
        "https://www.letour.fr/es/datos/datos-del-dia-etapa-21",
        "https://www.uci.org/article/uci-road-and-para-cycling-road-world-champs-pogacars-closing-masterclass/fvr4cXIs9lVch7ZQ7PGCa",
        "https://www.procyclingstats.com/statistics/grandtours/most-wins",
        "https://www.procyclingstats.com/statistics/grandtours/most-stage-wins",
    ],
    "TOOTS — Toots Thielemans": ["https://www.arts.gov/honors/jazz/jean-baptiste-toots-thielemans"],
    "HERGÉ — Georges Remi": [
        "https://www.tintin.com/en/herge",
        "https://www.tintin.com/nl/news/6394/the-secrets-of-herge-studios-behind-the-scenes-of-tintin",
    ],
    "RUBENS — Peter Paul Rubens": ["https://rubenshuis.be/en/stories/biography-rubens"],
}

# Per naamgever: bestandssleutel, naam, (accurate, publieke) discipline/levensjaren en
# een vaste omschrijvingsregel ("wie is dit"), alles meertalig.
meta = {
    "BREL — Jacques Brel":       {"key": "brel",   "naam": "Jacques Brel",
        "discipline": {"nl": "Chansonnier · 1929–1978", "fr": "Chanteur, auteur-compositeur · 1929–1978", "en": "Singer-songwriter · 1929–1978"},
        "omschrijving": {"nl": "Belgische chansonnier die wereldfaam verwierf met zijn Franstalige liederen.",
                          "fr": "Chansonnier belge devenu mondialement célèbre pour ses chansons en français.",
                          "en": "Belgian singer-songwriter who won worldwide fame with his French-language chansons."}},
    "HORTA — Victor Horta":      {"key": "horta",  "naam": "Victor Horta",
        "discipline": {"nl": "Architect · 1861–1947", "fr": "Architecte · 1861–1947", "en": "Architect · 1861–1947"},
        "omschrijving": {"nl": "Belgische architect en grondlegger van de art nouveau.",
                          "fr": "Architecte belge et pionnier de l’Art nouveau.",
                          "en": "Belgian architect and pioneer of Art Nouveau."}},
    "MERCKX — Eddy Merckx":      {"key": "merckx", "naam": "Eddy Merckx",
        "discipline": {"nl": "Wielrenner · °1945", "fr": "Coureur cycliste · °1945", "en": "Racing cyclist · b. 1945"},
        "omschrijving": {"nl": "Belgische wielrenner, door velen beschouwd als de beste aller tijden.",
                          "fr": "Coureur cycliste belge, considéré par beaucoup comme le meilleur de tous les temps.",
                          "en": "Belgian cyclist, regarded by many as the greatest of all time."}},
    "TOOTS — Toots Thielemans":  {"key": "toots",  "naam": "Toots Thielemans",
        "discipline": {"nl": "Jazzmuzikant · 1922–2016", "fr": "Musicien de jazz · 1922–2016", "en": "Jazz musician · 1922–2016"},
        "omschrijving": {"nl": "Belgische jazzlegende die de mondharmonica naar de wereldtop bracht.",
                          "fr": "Légende belge du jazz qui a porté l’harmonica au sommet mondial.",
                          "en": "Belgian jazz legend who brought the harmonica to the world stage."}},
    "HERGÉ — Georges Remi":      {"key": "herge",  "naam": "Hergé (Georges Remi)",
        "discipline": {"nl": "Striptekenaar · 1907–1983", "fr": "Auteur de bande dessinée · 1907–1983", "en": "Comics artist · 1907–1983"},
        "omschrijving": {"nl": "Belgische striptekenaar en geestelijke vader van Kuifje.",
                          "fr": "Auteur de bande dessinée belge et père de Tintin.",
                          "en": "Belgian comics artist and creator of Tintin."}},
    "RUBENS — Peter Paul Rubens":{"key": "rubens", "naam": "Peter Paul Rubens",
        "discipline": {"nl": "Kunstschilder · 1577–1640", "fr": "Peintre · 1577–1640", "en": "Painter · 1577–1640"},
        "omschrijving": {"nl": "Antwerpse barokmeester, de invloedrijkste schilder van zijn tijd.",
                          "fr": "Maître baroque anversois, le peintre le plus influent de son époque.",
                          "en": "Antwerp Baroque master, the most influential painter of his era."}},
}

OUT = Path(__file__).parent

for person, items in facts.items():
    m = meta[person]
    doc = {
        "schema": "companion.v1",
        "naamgever": {
            "naam": m["naam"],
            "discipline": m["discipline"],
            "omschrijving": m["omschrijving"],   # vaste "wie is dit"-regel (toont altijd)
            # weetjes = array; de companion kiest er willekeurig één uit
            "weetjes": [{"nl": it["NL"], "fr": it["FR"], "en": it["EN"]} for it in items],
        },
        "bronnen": sources.get(person, []),
    }
    p = OUT / f"companion-{m['key']}.json"
    p.write_text(json.dumps(doc, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {p.name:28s} {len(doc['naamgever']['weetjes'])} weetjes")

print(f"\nKlaar: {len(facts)} documenten, {sum(len(v) for v in facts.values())} weetjes x 3 talen.")
